services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: odoo18
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U odoo -d odoo18"]
      interval: 5s
      timeout: 3s
      retries: 60
    restart: unless-stopped

  odoo:
    image: odoo:18.0
    depends_on:
      - db
    # env ist optional, Odoo liest aus odoo.conf â€“ lassen wir aber drin, schadet nicht
    environment:
      HOST: db
      PORT: "5432"
      USER: odoo
      PASSWORD: password
      DATABASE: odoo18
    volumes:
      - odoo-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf:ro
    ports:
      - "8069:8069"
    restart: unless-stopped

volumes:
  pgdata:
  odoo-data:
